name: CheckMkDocsBuild

on:
  pull_request_target:
    branches:
      - master

jobs:
  build-docs:
    uses: Telucero/workflows/.github/workflows/mkdocs-build.yml@main
    with:
      mkdocs_repo: papermoonio/moonbeam-mkdocs
      docs_dir: moonbeam-docs
    secrets:
      token: ${{ secrets.REPO_SCOPED_TOKEN }}
